apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin-sa
      containers:
        - name: toolbox
          image: {{ .Values.deployment.images.toolbox }}
        - name: httpbin
          image: {{ .Values.deployment.images.httpbin }}
        - name: envoy
          image: {{ .Values.deployment.images.envoy }}
          volumeMounts:
            - name: envoy-conifg
              mountPath: /etc/envoy
              readOnly: true
            - name: spiffe-workload-api
              mountPath: /opt/spire/sockets
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: envoy-conifg
          configMap:
            name: httpbin-configmap
            items:
              - key: envoy-config
                path: envoy.yaml
