apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: httpbin
  ports:
    - name: envoy-secure
      protocol: TCP
      port: {{ .Values.service.securePort }}
      targetPort: {{ .Values.service.securePort }}
    - name: envoy-unsecure
      protocol: TCP
      port: {{ .Values.service.unsecurePort }}
      targetPort: {{ .Values.service.unsecurePort }}
