apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      serviceAccountName: beacon-sa
      containers:
        - name: beacon
          image: {{ .Values.images.beacon }}
        - name: toolbox
          image: {{ .Values.images.toolbox }}
        - name: envoy
          image: {{ .Values.images.envoy }}
          ports:
            - containerPort: {{ .Values.service.envoyPort }}
          volumeMounts:
            - name: envoy-conifg
              mountPath: /etc/envoy
              readOnly: true
            - name: spiffe-workload-api
              mountPath: /opt/spire/sockets
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: envoy-conifg
          configMap:
            name: beacon-configmap
            items:
              - key: envoy-config
                path: envoy.yaml
