apiVersion: v1
kind: Service
metadata:
  name: beacon-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: beacon
  ports:
  - name: beacon-envoy
    protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.service.envoyPort }}
