apiVersion: v1
kind: Service
metadata:
  name: beacon-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: beacon
  ports:
    - name: beacon-envoy-secure
      protocol: TCP
      port: {{ .Values.service.securePort }}
      targetPort: {{ .Values.service.securePort }}
    - name: beacon-envoy-unsecure
      protocol: TCP
      port: {{ .Values.service.unsecurePort }}
      targetPort: {{ .Values.service.unsecurePort }}
