apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          image: gcr.io/spiffe-io/wait-for-it
          args: ["-t", "60", "spire-server-service:8081"] # wait for spire-server to be ready
      containers:
        - name: spire-agent
          image: ghcr.io/spiffe/spire-agent:1.6.1
          volumeMounts:
            - name: spire-agent-config
              mountPath: /opt/spire/conf/agent
            - name: spire-agent-data
              mountPath: /opt/spire/.data
            - name: spire-token
              mountPath: /var/run/secrets/tokens
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
      volumes:
        - name: spire-agent-config
          projected:
            sources:
              - configMap:
                  name: spire-server-root-cert
              - configMap:
                  name: spire-agent-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: DirectoryOrCreate
        - name: spire-agent-data
          emptyDir: {}
        - name: spire-token
          projected:
            sources:
              - serviceAccountToken:
                  path: spire-agent
                  expirationSeconds: 7200
                  audience: spire-server
