apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-csi-driver
  namespace: {{ .Release.Namespace }}