apiVersion: v1
kind: Service
metadata:
  name: spire-server-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: spire-server
spec:
  type: NodePort
  selector:
    app: spire-server
  ports:
    - name: tcp
      port: 8081
      targetPort: 8081