clusterName: kind-cluster

deployment:
  name: unknown
  images:
    httpbin: kennethreitz/httpbin:latest
    toolbox: ghcr.io/troydai/beacon-toolbox:v0.21.0
    envoy: envoyproxy/envoy:v1.25.1

service:
  securePort: 9090
  unsecurePort: 9091

spiffe:
  trustDomain: spire-in-a-box.troydai.cc

authorization:
  allowedExact:
