---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prober-config
  namespace: workload-ns
data:
  beacon_addr: "localhost:7000"
  prober_interval: "10s"
  envoy-config: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 7000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: beacon-service
                virtual_hosts:
                - name: beacon-service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/grpcbeacon.Beacon"
                      grpc: {}
                    route:
                      cluster: beacon-service
      clusters:
      - name: beacon-service
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        http2_protocol_options: {}
        load_assignment:
          cluster_name: beacon-service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: beacon-service
                    port_value: 9090