apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prober
  template:
    metadata:
      labels:
        app: prober
    spec:
      serviceAccountName: prober-sa
      containers:
        - name: toolbox
          image: {{ .Values.images.toolbox }}
        - name: envoy
          image: {{ .Values.images.envoy }}
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            - name: spiffe-workload-api
              mountPath: /opt/spire/sockets
              readOnly: true

      volumes:
        - name: envoy-config
          configMap:
            name: prober-config
            items:
              - key: envoy-config
                path: envoy.yaml
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
